### ISSUE TITLE
multiple successive subscriptions cause server to not responds.

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#680] opened 2019-01-14 12:21 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
multiple successive subscriptions cause server to not responds.
a delay of few seconds between subscriptions make it more stable ..but still it is an issue .
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
multiple successive subscriptions should work.

**Comment by Jannis** [comment] 2019-01-14 12:58
@lutter Is this something you could try to reproduce?

**Comment by orenyodfat** [comment] 2019-01-14 12:59
yes.
just subscribe is a loop 10 times
will not always success.

**Comment by lutter** [comment] 2019-01-22 00:19
I've been trying to reproduce this, not to much avail. I put together this [gist](https://gist.github.com/lutter/a4bf2279c9295f7133a86e65dfe931cd) (check it out as a git repo) based on the test code from [daostack](https://github.com/daostack/subgraph/pull/64)

The only way I could get the repeated subscription fail was by making the timeout for async too small (resulting in a `Async callback was not invoked within the 2500ms timeout specified`), but could not find any other failures.

Maybe PR #648 did fix this issue, as noted on daostack issue 58? Could you either close this issue, or provide more detail on what failures you are seeing?

**Comment by orenyodfat** [comment] 2019-01-22 07:10
@lutter pr #648 did not solve the issue.
successive subscriptions should not fail even there is no timeout (0) between each.
looking at the gist you paste ...I am not sure to which events you are subscribing... I guess the test should be   : 
- subscribe to event
- trigger the event
- read and verify the subscription done its work

**Comment by lutter** [comment] 2019-01-22 19:38
I've updated the gist to run against our staging deployment. That might make it a little easier to understand what's happening there. The code in the gist is a slight adaptation of your `tests/integration/Subscription.spec.ts` and runs the single subscribe/receive event cycle that that test does in a loop (rather than having a loop in the shell do the repetition) There's no intentional pause between the repetitions, though they are done sequentially, just as noted in the daostack issue cited above. We could make the code in the gist do all this all in parallel, but it would be a deviation from what the initial bug report stated.

The timeout covers the amount of time it takes to establish a connection to the server, subscribe to a query, and receive the first result from that subscription. Therefore, you do need some sort of timeout, and the timeout is sensitive to how long it takes to do the above steps, which depends on a variety of factors (latency/bandwidth between you and the server, load on the server, complexity of the query etc.)

In graph-node, subscriptions let you register queries whose results may change as graph-node ingests more eth blocks; other than that, there's not really a way to trigger events from the outside. The 'trigger the event' in your description would require transacting something in Ethereum, which would of course require a much longer timeout as we'd have to wait for that transaction to show up on the chain.

To help clear this up, could you describe in more detail what behavior you think is incorrect here?

**Comment by orenyodfat** [comment] 2019-01-22 19:49
We are reproducing the issue on ganache..where the event triggering is fast enough to make the  graph node server unable to serve subscription any more..
the graph server should be able to handle many subscription at once...(at least not to be stack).

**Comment by lutter** [comment] 2019-01-22 20:53
What error exactly are you getting? Is the server denying connections when successive subscription requests are made? Is it just taking a long time to send back the initial response? If so, how long is it taking in your testing?

I assume when you are using ganache, you are ingesting blocks very rapidly. How loaded is the machine from that, without serving any subscriptions? I am doing a bunch of work to reduce the overhead of handling subscriptions, so getting these details is very interesting for that work, too.

**Comment by orenyodfat** [comment] 2019-01-23 09:12
Please see the issue on travis here :  daostack/subgraph#64 
The server in this case stop responding ...
@jellegerbrandy , could you please add your insight ..?

**Comment by jellegerbrandy** [comment] 2019-01-23 10:05
Hi @lutter .

The erroneous behavior we are seeing is: the server stops responding to subscriptions completely. It doees not seem to depend on the client: both the tests and not from the graphiql node will show this behavior. I am not seeing any particular errors, either from the client or in the graphql error log.

I've ran you gist test, and indeed it works fine.  We are, of course, running aagains a local installation of the graph-node  that runs in a docker container. I'll set up a small repo for the error (including a docker-compose file) so it will be easier to reproduce for you than running our complete subgraph test suite (it may also help us to track down the error)

**Comment by jellegerbrandy** [comment] 2019-01-24 08:44
I've tried in many ways, but I cannot reproduce the error anymore using the most recent `graphprotocol/graph-node:latest`  image from docker hub. 

I am not sure why the error continued persisting in our tests. We may have been working with  outdated `graphprotocol/graph-node:latest` images (it is easy to forget that you need do do an explicit `docker pull` to get the latest `:latest` image of today, and in fact I did forget) - but we were also seeing this behvior on travis, which does not cache the images. 

Despite these mysteries, i'd consider the error fixed.  Sorry about the confusion, and many thanks for your time, really appreciate the work your are doing :-)

**Comment by lutter** [comment] 2019-01-25 01:30
Thanks @jellegerbrandy for the update, and I am glad you aren't encountering this anymore! I'll close this for now. If you run into this issue again, feel free to reopen the issue.

**Closed by lutter** 2019-01-25 01:30 UTC
Labels: bug, to do
