### ISSUE TITLE
How does The Graph promised that it must received the incoming events? 

### ISSUE THREAD

**Issue by YamiOdymel** [graphprotocol/graph-node#2788] opened 2021-09-11 02:59 UTC
My company is trying to use `graph-node` as the indexing protocol in the NFT project which looks promising.

We know it re-sync/re-index the whole blockchain events when the `graph-node` service restarted,

But what happen if a network outage occurred? 

Since smart contract doesn't know if the subscriber received the events or not,

`graph-node` will missed the incoming events and those won't be replayed unless I restarted the `graph-node` service right? 

I didn't see the explanation in the [README](https://github.com/graphprotocol/graph-node) nor in the [Getting Started](https://github.com/graphprotocol/graph-node/blob/master/docs/getting-started.md) file,

Do I need to restart the `graph-node` service if I found an event was missing? But this doesn't sounds reliable.

---

Was trying to ask the question in Reddit but the `r/thegraph` looks more like it was targeted for investors.

**Comment by maoueh** [comment] 2021-09-13 15:10
> We know it re-sync/re-index the whole blockchain events when the graph-node service restarted,

That is not the expected behavior, `graph-node` tracks the progress using the latest block processed. It also deals with re-orgs and should be resistant to such conditions on the network.

> Since smart contract doesn't know if the subscriber received the events or not,

Events are retrieved from the blockchain node directly, specifying which block we are interested in, the smart contracts is not involved in this process at all. 

> graph-node will missed the incoming events and those won't be replayed unless I restarted the graph-node service right?

The is really no reason to miss any events, since it tracks the block progress, it knows where to continue and which events to request.

If it answers all your questions, feel free to close the issue. Use Discord channel (https://discord.gg/mbynFxVD) for support/question requests, there is a lot of people there that can answer your questions.

**Closed** 2021-09-14 01:49 UTC
