### ISSUE TITLE
graphnode logs lots of warning and becomes slow to respond after running tests often

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#964] opened 2019-05-26 09:07 UTC
https://github.com/daostack/subgraph/issues/242

**Comment by leodasvacas** [comment] 2019-05-27 15:22
What are the reproduction instructions? In what graph-node version this was reproduced?

**Comment by orenyodfat** [comment] 2019-05-29 07:26
v0.12.0 
no special instructions just start indexing.

**Comment by orenyodfat** [comment] 2019-05-29 07:26
v0.12.0 
no special instructions just start indexing. 
graph-node_1  | May 24 10:00:45.127 WARN Possible contention in tokio threadpool, code: TokioContention, timeout_ms: 1
graph-node_1  | May 24 10:00:45.137 WARN Possible contention in tokio threadpool, code: TokioContention, timeout_ms: 10
graph-node_1  | May 24 10:00:45.237 WARN Possible contention in tokio threadpool, code: TokioContention, timeout_ms: 100
graph-node_1  | component: Store
graph-node_1  |  May 24 10:00:45.533 WARN Possible contention in DB connection pool, wait_ms: 20
graph-node_1  |  May 24 10:00:46.057 WARN Possible contention in DB connection pool, wait_ms: 24
graph-node_1  | May 24 10:00:46.237 WARN Possible contention in tokio threadpool, code: TokioContention, timeout_ms: 1000
graph-node_1  |  May 24 10:00:46.451 WARN Possible contention in DB connection pool, wait_ms:

**Comment by leoyvens** [comment] 2020-05-15 14:10
Closing because this hasn't been reproduced in a long time, please open a new issue if this is still relevant.

**Closed by leoyvens** 2020-05-15 14:10 UTC
Labels: projects/daostack
