### ISSUE TITLE
Unable to index tenderly fork

### ISSUE THREAD

**Issue by skyao2002** [graphprotocol/graph-node#4356] opened 2023-02-12 08:56 UTC
Report a Bug

**What is the current behavior?**

I get the following warnings when trying to index tenderly fork rpc:

```
graph-node_1  | Feb 12 08:52:45.676 WARN Trying again after eth_getLogs RPC call for block range: [16177264..16178721] failed (attempt #10) with result Err(Transport(Code(400))), sgd: 1, subgraph_id: Qmb1Ase7uK7oe66fUDPvEpexUL42zoFaPA4cyLyvEw9LEA, component: BlockStream
graph-node_1  | Feb 12 08:52:45.676 WARN Unexpected RPC error, error: Transport(Code(400)), sgd: 1, subgraph_id: Qmb1Ase7uK7oe66fUDPvEpexUL42zoFaPA4cyLyvEw9LEA, component: BlockStream
```

The indexing goes really slowly or not at all, I have waited an entire day and it still had not indexed 100 blocks.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I start a graph node using docker-compose and the following docker-compose.yaml

```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - 172.23.0.1:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:https://rpc.tenderly.co/fork/53fea442-6f5a-4c23-9a03-918f0db9c824'
      GRAPH_LOG: info
      ETHEREUM_REORG_THRESHOLD: 1
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

**What is the expected behavior?**

Expected behavior is to index the rpc correctly.

**Comment by azf20** [comment] 2023-03-04 20:05
hey @skyao2002 I see you did configure the reorg threshold, does it index just very slowly? Do you get anything else in the logs except the two lines you shared?

**Comment by YarikRevich** [comment] 2023-04-01 01:08
@azf20 I tried to use goerli and mainnet Tenderly forks. The only thing I got to see is "Download Ethereum blocks may take a few minutes". I modified source code to see what is the block being registered at some moment. It got stuck at the first block(0). In my case no errors appear

**Comment by YarikRevich** [comment] 2023-04-01 01:08
REORG_THRESHOLD doesn't help in my case

**Comment by riordant** [comment] 2023-08-10 20:23
One thing to try is setting debug level to trace, which will give more verbose output. In my case it actually was syncing, just really slow when the devnet state became large (RPC calls slowed down to unusable levels).

**Comment by incrypto32** [comment] 2023-09-05 10:38
So i just reproduced the "slow" indexing, with debug level trace and the reason was the tenderly forks RPC itself

The subgraph would progress a bit then RPC calls would fail with `Internal Server Error`, Graph Node keeps retrying until it work for some time again and fails soon after. So my conclusion is that this is some sort of a rate limiting issue from tenderly.

``` component: BlockStream
Sep 05 16:06:03.337 WARN Unexpected RPC error, error: Rpc(Error { code: InternalError, message: "Internal server error", data: None }), sgd: 1, subgraph_id: QmXZiV6S13ha6QXq4dmaM3TB4CHcDxBMvGexSNu9Kc28EH, component: BlockStream
Sep 05 16:06:03.376 WARN Trying again after eth_getLogs RPC call for block range: [7674048..7675359] failed (attempt #10) with result Err(Rpc(Error { code: InternalError, message: "Internal server error", data: None })), sgd: 1, subgraph_id: QmXZiV6S13ha6QXq4dmaM3TB4CHcDxBMvGexSNu9Kc28EH, component: BlockStream

```

**Comment by incrypto32** [comment] 2023-10-24 13:15
Hi, We have been in touch with the Tenderly team, they have new version of forks coming out very soon, we got to test it out. It looks solid and they have addresses these RPC errors. Im closing this issue as it will be resolved with the new tenderly forks release.

**Closed by incrypto32** 2023-10-24 13:15 UTC

**Comment by skyao2002** [comment] 2023-10-24 13:32
Thanks for addressing this issue! I've been off this issue for a bit but will get to it in the future, so I appreciate the team figuring it out
