### ISSUE TITLE
Node gets "stuck" when syncing to a Parity archive node

### ISSUE THREAD

**Issue by iameli** [graphprotocol/graph-node#864] opened 2019-04-08 21:57 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Livepeer's graph ingest node gets "stuck" from time to time when it's set to sync to Livepeer's Parity archive node. Not impossible this is a bug in Parity or some sort of cross-toxicity in my particular configuration of Parity and Kubernetes networking... but we'll start here.

EDIT: I'm not sure how to find the exact graph-node version but it's whatever you get when you do `docker pull graphprotocol/graph-node@sha256:180e63288be14305feb7a825b0be41bf9b67f22ccc443781b598351455da6564`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Both the graph-nodes and the Parity node are running in a Kubernetes cluster on GCE. Here's a subset of how we're running Parity, for reference:

```
name: parity
image: parity/parity:v2.4.3
args:
  - --base-path=/home/parity/.local/share/io.parity.ethereum/
  - --tracing=on
  - --pruning=archive
  - --cache-size=8192
  - --jsonrpc-interface=all
  - --jsonrpc-apis=safe
```

The Parity node's JSON-RPC port is exposed as a service within the cluster. Then we set up our graph ingest node like so:

```
name: graph-ingest
resources:
  requests:
    memory: "2Gi"
image: graphprotocol/graph-node:latest
command:
  - /usr/local/cargo/bin/graph-node
  - --postgres-url=postgresql://postgres:[redacted]@127.0.0.1:5432/subgraph
  - --ethereum-rpc=mainnet:http://ethereum-rpc.default.svc.cluster.local:80
  - --ipfs=ipfs.default.svc.cluster.local:80
  - --ws-port=443
```

This proceeds to chug merrily along for hours, but then it gets stuck. The logs when it gets stuck look like this:

```
  block_number: 7529902
   block_hash: 0x6431c37e1974c4600485f8ab324f51d866de554b4376531acd5f3d6780d73537
    Apr 08 21:34:57.436 INFO Applying 0 entity operation(s)
component: BlockIngestor
 Apr 08 21:35:34.958 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:35:56.091 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:36:30.736 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:36:57.150 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:36:57.172 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
 Apr 08 21:37:09.890 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:37:09.914 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
 Apr 08 21:37:54.186 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:37:54.216 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
```

And even more oddly, it keeps happening after we restart the server:

```
component: SubgraphInstanceManager
 subgraph_id: Qmdfkii4bvs7JUujaReouAqSNNNycEsEUmTTcyrkMxk9ZU
  Apr 08 21:38:46.554 INFO Start subgraph
component: BlockIngestor
 Apr 08 21:38:46.556 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
 Apr 08 21:39:25.200 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:39:25.215 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
 Apr 08 21:39:45.870 WARN Trying again after block polling failed: Got invalid response: Error("EOF while parsing a value", line: 1, column: 0)
 Apr 08 21:39:45.897 INFO Downloading latest blocks from Ethereum. This may take a few seconds...
```

I've also reproduced the exact same behavior using the Websocket RPC interface instead of the JSON-RPC HTTP one.

The issue goes away completely if I instead use Infura to back the connection:

```
--ethereum-rpc=mainnet:https://mainnet.infura.io/v3/0663f21b67fd40cd989f86b44d7381c8
```

(No secrets there, that's the public Livepeer API key.)

I'm using Parity right now because that archive node synced first but I'll be able to test with Geth some time next week.

**What is the expected behavior?**

It work good

**Comment by olibearo** [comment] 2019-05-13 19:14
Hey @iameli, this error means that `parity-ethereum` is returning something that the `rust-web3` client isn't expecting.

Could you also paste the corresponding logs from the Parity Ethereum node when you run it with `--logging rpc=trace`?

**Comment by iameli** [comment] 2019-05-28 23:43
@olibearo Sure! Ran into this again today when I tried pointing our graph-node at a Parity node while going through our other problems. [Here's logs from both graph-node and Parity during a two-minute period where several EOFs were encountered](https://gist.github.com/iameli/93ee5f524a28d70dcfd5332944d083cd).

**Comment by iameli** [comment] 2019-07-24 19:52
Just reproduced and confirmed this is still happening with `graphprotocol/graph-node:v0.13.2` and `parity/parity:v2.5.5-stable`.

**Comment by abhayks1** [comment] 2019-07-25 07:05
Any update on this issue?
We are also facing the same issue with parity node. Below is the logs:
https://gist.github.com/abhayks1/a165538ff2daf52315ec8fdc82be6b40

**Comment by abhayks1** [comment] 2019-07-26 07:49
Update on the issue:
It's resolved with ropsten private geth node. 
The issue reappears with ropsten private parity node.

**Comment by leoyvens** [comment] 2019-08-06 16:05
Hi, this issue might be related https://github.com/graphprotocol/graph-node/issues/1025. The fix is not yet in a release, when we make a new graph-node release you should update and check if this is still occurring.

**Comment by leoyvens** [comment] 2020-02-27 19:19
Closing since this hasn't been reproduced in a long time.

**Closed by leoyvens** 2020-02-27 19:19 UTC
Labels: projects/livepeer
