### ISSUE TITLE
Subgraph composability 

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#296] opened 2018-08-25 23:12 UTC
Composability needs to exist at a few levels:

- Entity types should be able to reference entity types from other subgraphs
  - What invariants should we enforce on this?
- GraphQL queries should be able to reference entity types from multiple subgraphs
- Mappings will need to be able to reference data from other subgraphs
  - We should enable this through 2 API's:
     1) store.get() where we take an additional subgraph ID parameter
     2) store.query() which takes a GraphQL query
  - When we implement sharding we'll need to translate these calls to graph queries over the network
  - What invariants should we enforce on validators and SLA's to ensure that a given subgraph doesn't halt if query nodes are unavailable for dependent subgraphs?
- A hook should exist to run a handler on one subgraph when data matching a predefined filter is emitted in another subgraph

**Comment by Jannis** [comment] 2019-11-11 15:08
Duplicate of #1202 (+ subgraph pipelining, which we have on the roadmap).

**Closed by Jannis** 2019-11-11 15:08 UTC
Labels: area/graphql, area/store, area/subgraphs, epic, needs requirements
