### ISSUE TITLE
Decoding function inputs for an Ethereum call failed

### ISSUE THREAD

**Issue by ziegfried** [graphprotocol/graph-node#932] opened 2019-05-12 20:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Subgraph fails with error when attempting to decode some invalid inputs for an Ethereum function call. 

```
Subgraph instance failed to run: Failed to process trigger: Generating function inputs for an Ethereum call failed = Cannot decode bytes16, code: SubgraphSyncingFailure, id: QmcVgWVzeugoZjAdJHbKxD9Gt1FCB4cq2JzknoNKPdw9zN, updates: 0
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Clone https://github.com/ziegfried/peepeth-subgraph
2) Edit subgraph.yaml: Remove line-comment from `changeName(bytes16)` handler
```
        # - function: changeName(bytes16)
        #   handler: handleChangeName
```
3) Deploy

**What is the expected behavior?**

Graph node should ignore the invalid function call and keep processing the subgraph.

**Comment by Jannis** [comment] 2019-05-15 14:52
I've managed to reproduce this locally:
```
   block_number: 6774386
    block_hash: 0x7fe3891b67aea2e048d02d764b83019b21df764a391617d73fcaf88a43db06be
     May 15 16:51:55.304 INFO 1 trigger found in this block for this subgraph
     May 15 16:51:55.305 DEBG Start processing Ethereum call, to: 0xfa28…ce1d, data_source: Contract, handler: handleChangeName, function: changeName(bytes16)
     May 15 16:51:55.589 INFO Done processing Ethereum call, ms: 284, handler: handleChangeName, function: changeName(bytes16)
   component: BlockStream
    May 15 16:51:55.753 DEBG Requesting traces for block 6774518
    May 15 16:51:56.024 DEBG Received 261 traces for block 6774518
    May 15 16:51:56.025 DEBG Skipping 131 irrelevant block(s)
   block_number: 6774518
    block_hash: 0x58dd82c8082b627440289b1cbeb9fbe7c97269ddcffdcf3836487da0f18f9328
     May 15 16:51:56.033 INFO 1 trigger found in this block for this subgraph
   component: BlockStream
    May 15 16:51:56.035 DEBG Terminating chain head updates; channel closed
   May 15 16:51:56.036 ERRO Subgraph instance failed to run: Failed to process trigger: Generating function inputs for an Ethereum call failed = Cannot decode bytes16, code: SubgraphSyncingFailure, id: QmcBMXknjNmo2bZ3G3bqMYFkpZEcjUjV96CocMDnHxdKby
```

**Comment by Jannis** [comment] 2019-05-15 15:18
Transaction: https://etherscan.io/tx/0x837a8753e9b9d1a57a055b49b95ddbff85bdb1f099951e4289848bd490ddb171

Input data:
```
Etherscan:  0x5047b3376c65616465727300000000000000000000000000000000000000000000000000
Graph Node: 0x5047b337737475617274
```

So somehow our input data is different and invalid.

**Comment by olibearo** [comment] 2019-05-28 21:25
The problem here is that the [tx](https://etherscan.io/tx/0xacd6dc55d543ed6f0aaed7585d2b1a6bf885a0333febc2f32df7a20cb7a6dac0) has an input of `0x5047b337737475617274`. The function signature expects a `bytes16`, but after stripping off the first 4 bytes for the method id the function parameters data is only of length 6. 

The serialization library we use, [ethabi](https://github.com/graphprotocol/ethabi/), does not successfully deserialize the input because it is expecting 16 bytes. Solidity could be accepting the 6 byte input and padding it in the runtime to populate a `bytes16` for processing. 

I'm modifying ethabi to handle this.

**Comment by Jannis** [comment] 2019-06-26 18:30
This is worked on in https://github.com/graphprotocol/ethabi/pull/8.

**Comment by azf20** [comment] 2021-08-19 13:40
@Jannis & @fordN do you know if this is still a live issue? The Linked ethabi PR was closed

**Comment by leoyvens** [comment] 2022-01-25 16:23
Closing because this is old and seems fixed

**Closed by leoyvens** 2022-01-25 16:23 UTC
Labels: bug, chains/ethereum, p2, projects/peepeth
