### ISSUE TITLE
Missing blocks when running against kovan with infura 

### ISSUE THREAD

**Issue by timmclean** [graphprotocol/graph-node#507] opened 2018-10-19 21:28 UTC
@davekaj created a subgraph that seems to skip blocks sometimes when running against Kovan on Infura. Need to investigate further.

```
 Oct 19 16:58:47.053 DEBG Starting request for logs in block range [7400001,7410000]
 Oct 19 16:58:47.053 DEBG Starting request for logs in block range [7410001,7420000]
 Oct 19 16:58:47.053 DEBG Starting request for logs in block range [7420001,7430000]
 Oct 19 16:58:47.053 DEBG Starting request for logs in block range [7430001,7440000]
 Oct 19 16:58:47.053 DEBG Starting request for logs in block range [7440001,7450000]
 Oct 19 16:58:47.119 DEBG Received logs for [7440001, 7450000].
 Oct 19 16:58:47.122 DEBG Received logs for [7410001, 7420000].
 Oct 19 16:58:47.123 DEBG Received logs for [7430001, 7440000].
 Oct 19 16:58:47.123 DEBG Received logs for [7420001, 7430000].
 Oct 19 16:58:47.123 DEBG Received logs for [7400001, 7410000].
component: SubgraphInstanceManager
 component: BlockStream
  subgraph_name: dharma
   subgraph_id: QmbnH6gDNtEb49UwFzcQH3i5DfCUnTmjEX2x3C6yafRmj7
    Oct 19 16:58:47.123 DEBG Done finding next blocks.
    Oct 19 16:58:47.123 DEBG Found 33 block(s) with events.
    Oct 19 16:58:47.123 DEBG Requesting 33 block(s) in parallel...
    Oct 19 16:58:47.921 DEBG Skipping 7411958 block(s) with no relevant events...
```

```
 Oct 19 16:56:20.113 DEBG Starting request for logs in block range [7400001,7410000]
 Oct 19 16:56:20.113 DEBG Starting request for logs in block range [7410001,7420000]
 Oct 19 16:56:20.114 DEBG Starting request for logs in block range [7420001,7430000]
 Oct 19 16:56:20.114 DEBG Starting request for logs in block range [7430001,7440000]
 Oct 19 16:56:20.114 DEBG Starting request for logs in block range [7440001,7450000]
 Oct 19 16:56:20.161 DEBG Received logs for [7420001, 7430000].
 Oct 19 16:56:20.161 DEBG Received logs for [7440001, 7450000].
 Oct 19 16:56:20.162 DEBG Received logs for [7400001, 7410000].
 Oct 19 16:56:20.167 DEBG Received logs for [7430001, 7440000].
 Oct 19 16:56:20.168 DEBG Received logs for [7410001, 7420000].
component: SubgraphInstanceManager
 component: BlockStream
  subgraph_name: dharma
   subgraph_id: QmbnH6gDNtEb49UwFzcQH3i5DfCUnTmjEX2x3C6yafRmj7
    Oct 19 16:56:20.169 DEBG Done finding next blocks.
    Oct 19 16:56:20.169 DEBG Found 1 block(s) with events.
    Oct 19 16:56:20.169 DEBG Requesting 1 block(s) in parallel...
    Oct 19 16:56:20.282 DEBG Skipping 7420503 block(s) with no relevant events...
```

**Comment by davekaj** [comment] 2018-10-19 23:04
I'll add to this. 

Event `LogRepayment` came in at 98, 125, and 147 for attempt 1, 2, and 3
Event `LogDebtOrderFilled` came in at 169, 202, and 276

So it seems like it is across all events and all blocks, not just a specific event.

This query will look for the beneficiary, of which there should be 5 entries that pop up. 
```graphql
{
  debtOrders (where:{beneficiary:"0x16c51CcDB2f239c929CdA8E3E5309c19f3f799b4"}){
    id
    beneficiary
    issuanceCancelledBy
    collaterals{
      id
      status
      tokenAddress
      collateralReturnedTo
      amount
    }
}
}
```

I get between 0 and 5 each time I retry. I retry by dropping the database and creating a new database. 

I am currently syncing kovan locally. I will test it when it is done. Then we can narrow it down to possibly being a infura issue

**Comment by davekaj** [comment] 2018-10-20 15:10
I tested with a local Kovan node (note it was 18GB, and 6 hrs to download, if anyone wants to try themselves in the future).

It works well. 270 LogRepayment Events, 3 times in a row. So it appears the issue is with infura. With infura I got returned 98, 125, and 147 LogRepayment events.  It might only be infura kovan (they might deploy worse resources to maintaining it?) I will sync up my geth node , and test the mainnet dharma contracts to see what our results are. 

But regardless I would say Infura kovan is not safe to use, and I will get the details back on mainnet infura soon

Performance: Note that on my local node it took 13 seconds to process all 9 million kovan blocks. Infura took ~30 seconds, and it appears to skip blocks, so its at least 2.3 times faster. If infura is skipping blocks it is even faster technically. 
Note 36 and 13

**Comment by davekaj** [comment] 2018-10-20 16:09
Good news! Mainnet infura is consistent. 

LogRepayment showed up 398 three times in a row. Other events were consistent too. 

So it looks to me like we shouldn't rely on Infura for testnet querying. 

Can we close this issue with this conclusion?

**Comment by timmclean** [comment] 2018-10-20 16:13
Oh that's good news! I'd love to investigate a bit further to understand
which RPC calls exactly are unreliable on kovan

**Comment by davekaj** [comment] 2018-10-20 20:01
one theory I just had was it might be parities RPC calls. Since kovan only exists on parity we know we are hitting a parity node on infura kovan

It might be that our rpc calls work well with geth (and it might be that mainnet infura is only running geth)

**Closed** 2020-09-16 16:43 UTC
Labels: area/ethereum, bug, wontfix
