### ISSUE TITLE
[Bug] eth_call constantly reverting when called from the mapping handler

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-node#5035] opened 2023-12-01 10:13 UTC
### Bug report

Calling the `_badgeStore()` function is constantly reverting. I tried calling the same function through our polygon RPC using etherjs and I got response. 

Steps to reproduce:
1. Deploy https://github.com/itsjerryokolo/badge-subgraph
2. Check the logs

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by azf20** [comment] 2023-12-01 13:38
hey @itsjerryokolo are you calling the Polygon RPC at the specific block height?

Can you share the logs & the RPC call you're making?

**Comment by itsjerryokolo** [comment] 2023-12-01 13:50
@azf20 No, I didn't, but I tried it yesterday and got response. 
I tried again today in a new, more recent, event and it also failed. 
I got response again today when I tried through etherjs


This is the handler
```
export function handleProtocolSettingsUpdated(
	event: ProtocolSettingsUpdated
): void {
	const theBadgeAddress = event.address;
	const theBadge = Badge.bind(theBadgeAddress);
	const tbSTore = theBadge.try__badgeStore();

	if (!tbSTore.reverted) {
		let protocolConfigs = ProtocolConfig.load(tbSTore.value);

		if (!protocolConfigs) {
			protocolConfigs = new ProtocolConfig(tbSTore.value);
		}

		protocolConfigs.address = tbSTore.value;
		protocolConfigs.save();
	} else {
		log.warning("try__badgeStore reverted: {}", [
			event.transaction.hash.toHexString(),
		]);
	}
	```
	
It fires in this event
https://polygonscan.com/tx/0xa88a3c1648588a005e14d1aa57159675a2c4ca61cecfcabd8604db6d821481d5#eventlog

<img width="1006" alt="Screenshot 2023-12-01 at 2 48 46 PM" src="https://github.com/graphprotocol/graph-node/assets/73024324/747d43d3-5982-4cb7-ae5a-411685d7dc94">

**Comment by azf20** [comment] 2023-12-01 18:22
Thanks - can you share how you're calling with ethers.js?

**Comment by azf20** [comment] 2023-12-04 12:14
I can confirm that calling the function at the block returns a result as expected.

```
curl --location '<POLYGON-RPC>' \
--header 'Content-Type: application/json' \
--data '{
	"jsonrpc":"2.0",
	"method":"eth_call",
	"params":[{
		"to": "0xe6c5c3174439da7d2d60456ca7eb97e7dcd551e6",
		"data": "0x19b50c2a"
	}, {
        "blockHash": "0xa7cb86b9c8d68130f7003a1be9150ad25f7a113a866278d32d93ea47ab0f1910"
    }],
	"id":1
}'
```

@incrypto32 any idea what might be happening here which would prevent this call from returning as expected in the subgraph? Maybe something to do with the underscores?

**Comment by Agupane** [comment] 2023-12-05 18:07
Hi guys, we managed to fix the deployment issue, we don't know the cause but seems to be related to the graph-cli version, we updated it to version 0.62.0 and the deployment went through. The issue was only on polygon, other chains didn't had the issue. Thanks @itsjerryokolo for reporting it

**Comment by incrypto32** [comment] 2023-12-11 11:05
Closing this issue as it was related to the RPC provider and not graph-node itself.

**Closed by incrypto32** 2023-12-11 11:05 UTC
Labels: bug
