### ISSUE TITLE
BlockIngestor cannot get response when working on BSC 

### ISSUE THREAD

**Issue by 2129zxl** [graphprotocol/graph-node#4121] opened 2022-11-02 06:22 UTC
**Do you want to request a *feature* or report a *bug*?**
seems like a bug
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I used bsc(Implementation of the Ethereum standard) and run in local mode with the cmd:
```
cargo run -p graph-node --release -- \
  --postgres-url postgresql://***:***@localhost:5432/graph-node \
  --ethereum-rpc bsc:https://bsc-mainnet.****** \
  --ipfs 127.0.0.1:5002 \
  --debug
```

Here's my log on trace level:
```
INFO Downloading latest blocks from Ethereum, this may take a few minutes..., provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:41.764 TRCE Run with retry: eth_getBlockByHash RPC call for block hash 0xa411d2538101b4cb6f560289811a840b2e4b554746a66ca754fcd0138dc28f9f, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:42.221 TRCE Run with retry: batch eth_getTransactionReceipt RPC call for block 0xa411d2538101b4cb6f560289811a840b2e4b554746a66ca754fcd0138dc28f9f, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:44.672 WARN Trying again after block polling failed: 0xa411…8f9f, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:45.020 TRCE Running job, name: Vacuum subgraphs.subgraph_deployment, component: JobRunner
Nov 02 14:12:45.040 TRCE Running job, name: Report pg_notification_queue_usage(), component: JobRunner
Nov 02 14:12:45.675 TRCE BlockIngestor::do_poll, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:45.686 TRCE Run with retry: eth_getBlockByNumber(latest) no txs RPC call, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:45.876 INFO Downloading latest blocks from Ethereum, this may take a few minutes..., provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:45.876 TRCE Run with retry: eth_getBlockByHash RPC call for block hash 0x2712afdfb73b6582691e2099cf733fe42a8659aa031ff3fbae4c98cdf2624c43, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:46.233 TRCE Run with retry: batch eth_getTransactionReceipt RPC call for block 0x2712afdfb73b6582691e2099cf733fe42a8659aa031ff3fbae4c98cdf2624c43, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:48.956 WARN Trying again after block polling failed: 0x2712…4c43, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:49.960 TRCE BlockIngestor::do_poll, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:49.970 TRCE Run with retry: eth_getBlockByNumber(latest) no txs RPC call, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:50.190 INFO Downloading latest blocks from Ethereum, this may take a few minutes..., provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:50.190 TRCE Run with retry: eth_getBlockByHash RPC call for block hash 0xf68ac355682a95c02ac69a18cdda435e08621e7ded9d444a7706fc3d4bb12b58, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:50.953 TRCE Run with retry: batch eth_getTransactionReceipt RPC call for block 0xf68ac355682a95c02ac69a18cdda435e08621e7ded9d444a7706fc3d4bb12b58, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:53.457 WARN Trying again after block polling failed: 0xf68a…2b58, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:54.459 TRCE BlockIngestor::do_poll, provider: bsc-rpc-0, component: BlockIngestor
Nov 02 14:12:54.470 TRCE Run with retry: eth_getBlockByNumber(latest) no txs RPC call, provider: bsc-rpc-0, component: BlockIngestor
```

**What is the expected behavior?**

I cannot get the exact reason for the retrying. I tested the ethereum-rpc service in my local environment, it works well.
Is there any further info I can get from trace log?

**Comment by 2129zxl** [comment] 2022-11-03 16:38
It seems the same issue with #3537 ,any progress on this?

**Comment by azf20** [comment] 2023-03-20 09:12
hey @2129zxl are you still having this issue? Closing as a duplicate of #3537

**Closed by azf20** 2023-03-20 09:12 UTC
