### ISSUE TITLE
Errors decoding indexed strings

### ISSUE THREAD

**Issue by orenyodfat** [graphprotocol/graph-node#838] opened 2019-03-26 12:12 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
 Mar 26 12:10:32.603 ERRO Subgraph instance failed to run: Failed to process event: Failed to parse parameters of event: Register(address,string): Cannot decode string, id: QmV9i3tscEz24EZkkaQtffhzCJvut7rF5qiVhyd39BX8d7
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Comment by orenyodfat** [comment] 2019-03-26 12:14
similar to #801 which looks like it still not fixed

**Comment by Jannis** [comment] 2019-03-26 12:34
@orenyodfat #801 is fixed, but I realize that the comments conflate two different problems. The original bug reported in #801 had nothing to do with `indexed` event parameters, like I was suggesting. `indexed` event parameters are still a problem, see #731 and https://github.com/paritytech/ethabi/issues/146.

@orenyodfat Which commit of the DAOstack subgraph triggers this bug here?

**Comment by orenyodfat** [comment] 2019-03-26 13:08
@Jannis it is not committed yet . It indeed an indexed event param. Do you have an estimation? A work around ?

**Comment by Jannis** [comment] 2019-03-26 14:13
@orenyodfat A workaround could be to use `indexed bytes32` instead of `indexed string`. Then in the subgraph mapping you could do `someParam.toString()` to interpret the byte array as a string again.

I was thinking of tackling this next week but you're the second person to bring this issue up today, so I'm tempted to work on it sooner. Until I've decided, the estimate is: this or next week. 😄

**Comment by Jannis** [comment] 2019-03-28 10:40
I'll close this one as a duplicate of #731, since it's the same problem.

**Closed by Jannis** 2019-03-28 10:40 UTC
Labels: adoption-blocker, area/ethereum, bug, to do
