### ISSUE TITLE
[Bug] Node is "stuck" with Tenderly Goerli fork

### ISSUE THREAD

**Issue by YarikRevich** [graphprotocol/graph-node#4494] opened 2023-03-26 02:02 UTC
### Bug report

```Markdown
I have started graph node locally with such param: "--ethereum-rpc goerli:https://rpc.tenderly.co/fork/1817dc9c-3049-4377-9d2c-fd342afd9292" and it's stuck on "Downloading latest blocks from Ethereum".
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [X] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by azf20** [comment] 2023-03-31 22:23
hey thanks @YarikRevich I believe this is a duplicate of https://github.com/graphprotocol/graph-node/issues/4356

will get to the bottom of this!

**Closed by azf20** 2023-03-31 22:23 UTC
Labels: bug
