### ISSUE TITLE
@derivedFrom isn't working in all instances

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#232] opened 2018-08-01 18:29 UTC
We need to investigate when this doesn't work.

**Comment by fordN** [comment] 2018-08-09 19:52
After revisiting the adchain example I was able to get the @derivedFrom directive to work; effectively pulling `Challenges` into the `Application` type.  The solution to the difficulties I had getting the two-way relationship working appears to be clear, detailed documentation and a diverse set of example subgraphs to reference.

**Comment by Jannis** [comment] 2018-08-21 09:08
@fordN Is this not a bug then?

**Comment by Jannis** [comment] 2018-08-27 15:42
Closing, since we got this to work in the adchain subgraph and it wasn't a bug in the software.

**Closed by Jannis** 2018-08-27 15:42 UTC
Labels: area/graphql, bug, developer experience, pending review
