### ISSUE TITLE
Trouble running the local node with docker? Help/support request.

### ISSUE THREAD

**Issue by vyzaldysanchez** [graphprotocol/graph-node#2321] opened 2021-03-29 21:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Not really sure if it is a bug, but I'm trying to get some help/support into running a local node with the docker setup, as stated in [the docs](https://thegraph.com/docs/quick-start#local-development).

**What is the current behavior?**
When running `docker-compose up` after running the `./setup.sh` script in Linux I'm getting the following:

![Screenshot from 2021-03-29 17-46-01](https://user-images.githubusercontent.com/8971713/112904761-6dc56500-90b7-11eb-986c-05de03e4d04c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As stated previously, just cloning the repo, running the `setup` script for Linux, and then starting the containers. (Note that I already have ganache running)

Here's the `docker-compose.yml` content:

```yml
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: *****
      postgres_pass: *****
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://172.21.0.1:8545'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

**What is the expected behavior?**
The graph node should be running without issues locally (?).

Thanks in advance for the support,

**Comment by firke** [comment] 2021-03-31 16:02
What's the status of ipfs container? Try running `docker logs docker_ipfs_1`. Would think ipfs did not startup properly, example scenario would be that it not able to open up the 5001 port due to a clash, if you ran ipfs desktop/client previously?

**Comment by vyzaldysanchez** [comment] 2021-04-01 21:54
@firke this is the result of running `docker logs docker_ipfs_1`: 

```
Changing user to ipfs
ipfs version 0.4.23
Found IPFS fs-repo at /data/ipfs
Initializing daemon...
go-ipfs version: 0.4.23-6ce9a35
Repo version: 7
System version: amd64/linux
Golang version: go1.12.16
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.18.0.2/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.18.0.2/tcp/4001
API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready
```

**Comment by tilacog** [comment] 2021-04-02 17:59
@vyzaldysanchez It would be best to rule out the possibility of any firewall rule that could be stopping container-to-container communications. 

Could you please tell us which Linux distribution you are running this on and which firewall program might be running alongside graph-node?

**Comment by firke** [comment] 2021-04-06 10:19
To elaborate on @tilacog answer - you could try spinning up a separate network for these containers, seeing if the issue would persist. If your default network in docker is 'host', this could be why, e.g. UFW blocking or something else.
If you want to try with a separate network you could try:
1. Add the following snippet to each container specification:
`networks:
   - graph`
 2. Add the following at the bottom of the file:
 `networks:
    graph:
      name: graph
      ipam:
        driver: default
        config:
          - subnet: 172.16.30.0/24 # specify some other range if this overlaps`
          
This would create a separate network and attach containers to it, would rule out if there is something wrong with default network specified. For troubleshooting the network try `docker inspect network graph`, see which type of network is created.

**Comment by vyzaldysanchez** [comment] 2021-04-06 15:13
Thanks for your detailed responses and support.

I'll be doing all your suggestions regarding networking and letting you know the results later today.

Thanks again, I appreciate all the support.

**Comment by azf20** [comment] 2021-05-28 13:45
@otaviopace this looks like the same problem we were investigating yesterday?

**Comment by otaviopace** [comment] 2021-05-28 14:04
I don't think so @azf20 , this looks a problem specifically with networking on `tokio` and/or `ipfs`. The problem we were having is with the WebAssembly runtime when running mappings.

**Comment by azf20** [comment] 2021-06-01 12:45
@vyzaldysanchez closing this as we were not able to reproduce, but please do re-open if you are still having this problem! cc @tilacog

**Closed by azf20** 2021-06-01 12:45 UTC
