### ISSUE TITLE
Use TlsMode::Prefer instead of TlsMode:None in notification_listener

### ISSUE THREAD

**Issue by joe-bowman** [graphprotocol/graph-node#2097] opened 2020-12-26 11:56 UTC
In notification_listener, we create a postgresql connection with the param `TlsMode::None`. There is no reason to not use `TlsMode::Prefer` here and not force operators to run postgresql with `Host` over `SslHost` in pg_hba.conf.

https://github.com/graphprotocol/graph-node/blob/39287ae65a1827d0fbaf79cbc91844549ac00576/store/postgres/src/notification_listener.rs#L121

Elsewhere, `Diesel` is used and this respects the `postgres_url` passed on the command line.

**Comment by joe-bowman** [comment] 2020-12-26 15:20
Sadly, this is not as easy as it seems.

The postgres v0.15.2 library support for TLS requires an _old_ version of openssl - and upgrading runs into various issues (notably mutable borrowing of the Postgresql Client object for both Client.notifications() and a new JsonNotification object).

It'd be great to get this looked into, because disabling TLS for this feels the wrong thing to do..

**Comment by leoyvens** [comment] 2021-04-06 00:25
@joe-bowman are you still interested in this? We've since updated the `postgres` crate, if you want to try this again.

**Comment by qiaozhengyuan** [comment] 2021-05-08 09:38
Would hope this change gets deployed as when I tried to run the docker image with my own postgresql service, it failed because my postgresql enforces tls.

**Comment by wup-dps** [comment] 2022-04-02 15:28
Any update here? Does the graph-nodel support postgres over SSL?

**Comment by JasoonS** [comment] 2022-04-21 08:25
> Does the graph-node support postgres over SSL?

AFAIK not unfortunately. It is a big pity since most self maintained graphs would use a postgres instance that requires SSL.

**Comment by mb-shorai** [comment] 2022-04-21 13:05
> The postgres v0.15.2 library support for TLS requires an _old_ version of openssl - and upgrading runs into various issues (notably mutable borrowing of the Postgresql Client object for both Client.notifications() and a new JsonNotification object).

@joe-bowman how can one reproduce the issue?

**Comment by mb-shorai** [comment] 2022-05-03 08:57
I guess it can be closed now that https://github.com/graphprotocol/graph-node/pull/3503 is merged, although there is some room for improvements (e.g. don't turn the certificate validation off, but make it configurable).

**Closed** 2022-05-05 19:44 UTC
Labels: area/store
