### ISSUE TITLE
docker warnings in avalanche network 

### ISSUE THREAD

**Issue by ChameeraLR** [graphprotocol/graph-node#3061] opened 2021-12-13 17:12 UTC
**Do you want to request a *feature* or report a *bug*?**
   Bug

**What is the current behavior?**
   I am using https://hub.docker.com/r/graphprotocol/graph-node with avalanche network.
  below are logs in docker.

for the rpc url i used **https://api.avax.network/ext/bc/C/rpc**

 Dec 13 17:01:51.874 INFO Syncing 50 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 50, blocks_behind: 574, latest_block_head: 8192356, current_block_head: 8191782, provider: avalanche-rpc-0, component: BlockIngestor
**Dec 13 17:02:23.496 WARN Trying again after block polling failed: Got invalid response: Error("expected value", line: 1, column: 1), provider: avalanche-rpc-0, component: BlockIngestor**
Dec 13 17:02:24.552 INFO Syncing 50 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 50, blocks_behind: 590, latest_block_head: 8192372, current_block_head: 8191782, provider: avalanche-rpc-0, component: BlockIngestor
Dec 13 17:02:27.949 INFO Syncing 2 blocks from Ethereum., code: BlockIngestionStatus, blocks_needed: 2, blocks_behind: 2, latest_block_head: 8192374, current_block_head: 8192372, provider: avalanche-rpc-0, component: BlockIngestor
Dec 13 17:02:31.082 INFO Syncing 1 blocks from Ethereum., code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 8192375, current_block_head: 8192374, provider: avalanche-rpc-0, component: BlockIngestor
**Dec 13 17:03:13.527 WARN Trying again after block polling failed: Got invalid response: Error("expected value", line: 1, column: 1), provider: avalanche-rpc-0, component: BlockIngestor**
Dec 13 17:03:14.578 INFO Syncing 24 blocks from Ethereum., code: BlockIngestionLagging, blocks_needed: 24, blocks_behind: 24, latest_block_head: 8192398, current_block_head: 8192374, provider: avalanche-rpc-0, component: BlockInges

it gives a waring message.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

run the docker locally with avalanche network.

**What is the expected behavior?**

 should run without warnings

Can some one help me with this?

**Comment by azf20** [comment] 2021-12-14 20:10
are you able to share your exact docker compose, and any subgraphs you are trying to deploy?

**Comment by croc12344** [comment] 2021-12-15 05:30
I'm getting similar response on cronos-mainnet

Here's my docker compose 
```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    depends_on:
      - postgres
      - ipfs
    environment:
      postgres_host: postgres
      postgres_user: graphNode
      postgres_pass: docker
      postgres_db: graphDB
      GRAPH_LOG: info
      ipfs: "ipfs:5001"
      ethereum: "cronosmainnet_25-1:https://evm-cronos.crypto.org/"
      ETHEREUM_POLLING_INTERVAL: 1000
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: graphNode
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: graphDB
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs

```

@azf20

**Comment by tharinduk90** [comment] 2021-12-15 13:00
i use this.

1) i used the aws rds postgres db for the data base
2) to deploy the docker used the aws ec2

sudo docker run -it --network="host" \
	-e postgres_host=AWS_RDS_DATA_URL \
	-e postgres_port=5432 \
	-e postgres_user=AWS_RDS_POSTGRES_USER\
	-e postgres_pass=AWS_RDS_POSTGRES_PW\
	-e postgres_db=AWS_RDS_POSTGRES_DBNAME\
	-e ipfs=http://127.0.0.1:5001 \
	-e ethereum=avalanche:https://api.avax.network/ext/bc/C/rpc \
	graphprotocol/graph-node:latest

**Comment by azf20** [comment] 2022-01-07 12:48
This looks like an intermittent issue with the Avalanche endpoint, rather than an issue with Graph Node. When you deploy a subgraph, does it start indexing successfully? You can use `GRAPH_LOG: trace` to get more detailed logging. Closing this issue for now as it doesn't seem to be a Graph Node issue, but please re-open if you think the problem is with Graph Node

**Closed by azf20** 2022-01-07 12:48 UTC
