### ISSUE TITLE
Unable to connect to a postgres database that requires SSL/TLS

### ISSUE THREAD

**Issue by JasoonS** [graphprotocol/graph-node#3025] opened 2021-12-01 19:49 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Unable to connect to a hosted postgresql database in Digital ocean. On connection the graph node prints the following:

```
Failed to connect notification listener: error performing TLS handshake: no TLS implementation configured, retry_delay_s: 1, attempt: 0, channel: chain_head_updates, component: ChainHeadUpdateListener > NotificationListener
ERRO Postgres connection error, error: FATAL:  remaining connection slots are reserved for non-replication superuser connections, pool: main, shard: primary, component: ConnectionPool
```

This is using that latest graph-node master branch release.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

This error occurs using the standard hosted postgresql database from Digital Ocean.

**What is the expected behavior?**

It should be able to connect to a database that requires SSL.

**Comment by azf20** [comment] 2021-12-02 10:13
Thanks @JasoonS - to confirm, this is a general bug, not a regression with the new 0.25.0 graph-node? @lutter any ideas on this?

**Comment by JasoonS** [comment] 2021-12-03 05:13
@azf20 - I have tried both on a very recent stable release and on current master.

It is the first time I have tried to use digital ocean's postgres offering for the graph. Before I have always used the standard postgres docker image without any ssl settings.

So my guess is it is a general bug, and I think it is somehow related to how the posgres rust library you are using is configured.

**Comment by leoyvens** [comment] 2021-12-03 13:34
This is #2097

**Comment by azf20** [comment] 2022-01-07 12:50
Thanks @JasoonS! Closing as duplicate of #2097 ,

**Closed by azf20** 2022-01-07 12:50 UTC

**Comment by JasoonS** [comment] 2022-01-07 13:02
Thanks!
