### ISSUE TITLE
[Bug] Cosmos subgraph indexing wrong 'rewards' event

### ISSUE THREAD

**Issue by wojciechowskip** [graphprotocol/graph-node#4998] opened 2023-11-18 12:44 UTC
### Bug report

Hi guys,

I was trying to use cosmoshub subgraph on hosted service to index `rewards` and `proposer_rewards` events happening while distributing rewards to validators https://docs.cosmos.network/v0.50/build/modules/distribution#beginblocker.
High level description of events happening
`rewards` is event which happens every block and this is basically reward for attestation, since there are 180 active validators there should be around 180 `rewards` events per block
`proposer_reward` is an event which happens every block but only once, since there is only 1 block proposer chosen before block happens.

Unfortunately even if I am trying to track both events - I am ending up in a situation like both tracked events are resolved to `proposer_reward`. This can be easily reproduced using example in your documentation ->  https://github.com/graphprotocol/graph-tooling/tree/main/examples/cosmos-validator-rewards
Even if query per every block should return around 180 events (since we are not sure validators are always 100% responsive) it is returning only 1 event per block.

My subgraph.yaml:
```
specVersion: 0.0.5
description: Validator Delegations Example
schema:
  file: ./schema.graphql
dataSources:
  - kind: cosmos
    name: CosmosHub
    network: cosmoshub-4
    source:
      startBlock: 17680000
    mapping:
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - ValidatorReward
      eventHandlers:
        - event: rewards
          handler: handleReward
        - event: proposer_reward
          handler: handleProposerReward
      file: ./src/mapping.ts
```
      
My mapping.ts:
```
export function handleReward(data: cosmos.EventData): void {
  const height = data.block.header.height;

  const amount = data.event.getAttributeValue('amount');
  const validator = data.event.getAttributeValue('validator');

  let reward = new ValidatorReward(`${height}-${validator}`);

  reward.amount = amount;
  reward.validator = validator;
  reward.blockHeight = `${height}`;

  reward.save();
}

export function handleProposerReward(data: cosmos.EventData): void {
  const height = data.block.header.height;

  const amount = data.event.getAttributeValue('reward');
  const validator = data.event.getAttributeValue('validator');

  let reward = new ValidatorProposerReward(`${height}-${validator}`);

  reward.amount = amount;
  reward.validator = validator;
  reward.blockHeight = `${height}`;

  reward.save();
}
```

My schema:
```
type ValidatorReward @entity {
  id: ID!
  amount: String!
  validator: String!
  blockHeight: String!
}

type ValidatorProposerReward @entity {
  id: ID!
  amount: String!
  validator: String!
  blockHeight: String!
}
```

Example query:
```
query MyQuery {
  validatorRewards(
    first: 10
    where: {blockHeight: "17860023"}
  ) {
    amount
    blockHeight
    validator
  }
  validatorProposerRewards(
    first: 10
    where: {blockHeight: "17860023"}
  ) {
    amount
    blockHeight
    validator
  }
}
```

Output from query:
```
{
  "data": {
    "validatorRewards": [
      {
        "amount": "613251.550000000000000000uatom",
        "blockHeight": "17860023",
        "validator": "cosmosvaloper1z8zjv3lntpwxua0rtpvgrcwl0nm0tltgpgs6l7"
      }
    ],
    "validatorProposerRewards": [
      {
        "amount": "",
        "blockHeight": "17860023",
        "validator": "cosmosvaloper1z8zjv3lntpwxua0rtpvgrcwl0nm0tltgpgs6l7"
      }
    ]
  }
}
```
Problems:
1) As you can see in attached output - even if we index `rewards` event there is only one per block - which is not true since there is always around 180 and we can confirm by querying the network
```NODE_RPC_ADDRESS/block_results?height=17860023``` (If node was not historical it may be hard to achieve so old data, but every block returns around 180 events of this type)
What is more validator address related to this indexed `rewards` event points to an address which did a proposal in this block. So looks like `rewards` event is trying to point `proposer_reward` what can be true since there was only one event of that type in this block (and in every other block as well there is only 1).
2) And the second problem is that if we index `proposed_reward` and try to extract reward attribute we miss value. Key of this attribute should be 'reward' according to https://docs.cosmos.network/v0.50/build/modules/distribution#beginblocker
![image](https://github.com/graphprotocol/graph-node/assets/32172774/0cf5e4f5-96d8-40aa-8e17-fc2c7368c30f)
But after some of my tests it looks like it's under 'amount' attribute. Not sure if subgraph is wrong or cosmos documentation is outdated.

Thanks in advance, if needed I can provide more information but I think it should be clear what is the issue and can be easily reproduced even by using example: https://github.com/graphprotocol/graph-tooling/tree/main/examples/cosmos-validator-rewards.

### Subgraph name or link to explorer

https://thegraph.com/hosted-service/subgraph/wojciechowskip/cosmoshub-4

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by cometcrafter** [comment] 2023-11-21 07:58
Block data from firehose looks fine for this. Looks like it could be an issue in the Graph node end. I'll try to dry-run the logic to find what's the root cause behind this.

**Comment by wojciechowskip** [comment] 2023-12-20 10:17
Hi @cometcrafter, how is it going? :)
Using the graph for Cosmos I've also realized ```MsgWithdrawDelegatorReward``` is not present after indexing, meaning that the graph is also failing to catch this one.

**Comment by matthewdarwin** [comment] 2024-01-06 16:49
I believe this issue is fixed with the solution for https://github.com/graphprotocol/graph-node/issues/5111

@alex-pakalniskis pls close.

**Closed** 2024-02-02 12:38 UTC
Labels: bug
