### ISSUE TITLE
How to re-sync several subgraphs 

### ISSUE THREAD

**Issue by suricata3838** [graphprotocol/graph-node#2561] opened 2021-06-11 03:56 UTC
**Do you want to request a *feature* or report a *bug*?**
bug-like behavior    

**What is the current behavior?**
Currently only one subgraph is synced and others aren't synced any more with a local graph-node.   

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I deployed a local graph-node on docker. The environment variables are below.   

```
ethereum=
bsc:full,archive:https://apis.ankr.com/<id>/binance/archive/main
GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH=y
ipfs=localhost:5001
postgres_host=<postgres_host>
postgres_db=graph
postgres_user=<user>
postgres_pass=<pw>
``` 

Then deployed 4 subgraphs. Currently one subgraph is synced, but others aren't synced.
I can check the healths through `:8030/graphql`.
When I query `indexingStatusForCurrentVersion`, 
The response of synced subgraph is 
```
{
  "data": {
    "indexingStatusForCurrentVersion": {
      "chains": [
        {
          "chainHeadBlock": {
            "number": "8193638"
          },
          "latestBlock": {
            "number": "4400811"
          }
        }
      ],
      "fatalError": null,
      "health": "healthy",
      "synced": true
    }
  }
}
```

Those of others are

```
{
  "data": {
    "indexingStatusForCurrentVersion": {
      "chains": [
        {
          "chainHeadBlock": {
            "number": "8193638"
          },
          "latestBlock": {
            "number": "7261172"
          }
        }
      ],
      "fatalError": null,
      "health": "healthy",
      "synced": false
    }
  }
}
```

**What is the expected behavior?**
Several subgraphs are syncing concurrently.

I'm not sure this behavior is default or not. I wanna increase subgraphs and make all of them syncing all at once.
Could anyone help me or give me suggestions?

**Comment by schmidsi** [comment] 2021-06-11 12:53
Thanks for the report. As far as I can see, one of your subgraphs is already synced and the others are currently syncing. This is expected behaviour.

Syncing can take a long time, several days in fact for complex subgraphs.

I'm closing this, because I think your question is answered. If not, feel free to reopen and follow up.

**Closed by schmidsi** 2021-06-11 12:53 UTC
