### ISSUE TITLE
[Bug] Occasional extremely slow query processing

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-node#4931] opened 2023-10-23 17:16 UTC
### Bug report

Occasionally, processing fairly simple queries like this one for [uniswap](https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3)
```graphql
query priceByBlock {
  token(
    id: "0x3432b6a60d23ca0dfca7761b7ab56459d9c964d0"
    block: { number: 18413853 }
    subgraphError: allow
  ) {
    derivedETH
    volumeUSD
  }
}
```

can take very long. Generally, the query takes 20ms or so, but sometimes it takes 1.5s - rerunning the query 10-20 times usually leads to a slow instance. Looking at query traces, the query spends very little time with SQL queries (say 5ms) and the rest of the time somewhere in query processing.

It looks very much like this is caused by some sort of resource contention, maybe one of the cache locks, the query semaphore or the connection pool. It could of course also be caused by other elements in the stack, like proxy servers.

I ruled out the load manager as that uses a `RwLock` by turning it off - that did not change the symptoms.

### Relevant log output

Here's a query trace of a slow invocation:
```json
{
  "data": {
    "token": {
      "derivedETH": "0.0033016218795969302566912937428371",
      "volumeUSD": "578792521.1437912970985064082900814"
    }
  },
  "trace": {
    "query": "query priceByBlock { token(id: \"0x3432b6a60d23ca0dfca7761b7ab56459d9c964d0\", block: {number: 18413855}, subgraphError: allow) { derivedETH volumeUSD } } ",
    "query_id": "e07bf8d2ded9f92e-74d1a7541c302694",
    "block": 18413855,
    "elapsed_ms": 529,
    "token": {
      "query": "/* controller='filter',application='sgd582965',route='e07bf8d2ded9f92e-74d1a7541c302694',action='18413855' */\tselect 'Token' as entity, to_jsonb(c.*) as data from (select  c.*\t  from \"sgd582965\".\"token\" c\t where c.block_range @> $1 and coalesce(upper(\"block_range\"), 2147483647) > $2 and lower(\"block_range\") <= $3 and c.\"id\" = $4\t\t \t limit 100) c -- binds: [18413855, 18413855, 18413855, \"0x3432b6a60d23ca0dfca7761b7ab56459d9c964d0\"]",
      "elapsed_ms": 5,
      "entity_count": 1
    }
  }
}
```

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

None

**Comment by leoyvens** [comment] 2023-11-21 14:50
We've done some ops work that has improved request latencies and DB connection contention on hosted, which is where this was reproduced. So while I didn't root cause where the slowness was for this issue, it would be interesting to check if it still reproduces.

**Comment by leoyvens** [comment] 2023-12-16 12:06
Closing but feel free to reopen if this reproduces again.

**Closed by leoyvens** 2023-12-16 12:06 UTC
Labels: bug

**Comment by lutter** [comment] 2023-12-19 20:01
I just tried the query (without a block constraint to query the latest block) and response times seem to be very consistent now

**Comment by siricol** [comment] 2024-03-22 01:59
@lutter how did you sync graph node? locally with Geth?
