### ISSUE TITLE
Feature Request : 'AND' and 'OR' operators on filtering

### ISSUE THREAD

**Issue by ebgd** [graphprotocol/graph-node#2133] opened 2021-01-22 21:21 UTC
request a *feature* 

Is it possible to filter with "and" and "or" operators, or combination of those operators
Like in :
where: {a_not:"x" OR b_not:"y"} )
or 
where: {a_not:"x" AND b_not:"y"} )

**Comment by leoyvens** [comment] 2021-01-22 21:33
Thanks for the request, this is a duplicate of #579.

**Closed by leoyvens** 2021-01-22 21:33 UTC
