### ISSUE TITLE
latest docker-compose still results in locale C error 

### ISSUE THREAD

**Issue by voyenavion** [graphprotocol/graph-node#4539] opened 2023-04-13 20:29 UTC
### Bug report

I'm running your latest docker-compose with a modification to have it connect to my custom evm chain and I keep getting the same error:
 `thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:988:13 `
 
 this issue has been raised and closed before but I'm still encountering it. 
 
 I'm running it on a mac OS 11.7.1

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by maoueh** [comment] 2023-04-13 20:57
Maybe your database was already existing and thus didn't had the right locale? Seems the https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml#L47 is there, do you see it in your file?

**Comment by voyenavion** [comment] 2023-04-14 13:27
thanks for joining the conversation, Maoueh. yes, i see that line in my docker-compose. I was doing `docker-compose down -rmi all -v ` between tries so I don't think the postgres container could already have that db. do you mean existing somewhere else, like on my local?

**Comment by llllvvuu** [comment] 2023-05-26 22:07
You need to `rm -rf data`

Otherwise the culprit is this line (you can verify it because removing this line without `rm -rf data` also works but is probably not ideal because you lose caching - but then it again it might also be ideal because `graph-node` tends to be really flaky in local dev if I don't delete `data/` every run)

```
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
 ```

**Comment by neysofu** [comment] 2023-06-06 11:57
Both @maoueh and @llllvvuu 's suggestions are good, deleting `data/` should get you a pristine database!

Closing this because it seems like the issue is with the local volumes configuration, as opposed to the `docker-compose.yml` manifest.

**Closed by neysofu** 2023-06-06 11:57 UTC
Labels: bug
