### ISSUE TITLE
With similarly named events, we create duplicate types 

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#736] opened 2019-02-05 03:49 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Decentraland has 2 events named `Transfer`, with different fields. But our graph-ts type creation makes 2 types, causing compiling errors

**What is the expected behavior?**

Name them Transfer1 and Transfer2, or something similar. 

Related to these two issues :
https://github.com/graphprotocol/graph-cli/issues/168
https://github.com/graphprotocol/graph-cli/issues/167

**Comment by Jannis** [comment] 2019-04-08 16:04
Duplicate of https://github.com/graphprotocol/graph-cli/issues/168.

**Closed by Jannis** 2019-04-08 16:04 UTC
Labels: adoption-blocker, area/cli, area/ethereum, bug
