### ISSUE TITLE
Duplicate Indexes

### ISSUE THREAD

**Issue by akme** [graphprotocol/graph-node#2028] opened 2020-11-25 21:34 UTC
pghero says "These indexes exist, but aren’t needed. Remove them for faster writes."

On subgraph_deployment
```
attr_2_0_subgraph_deployment_id (id)
```
is covered by
```
subgraph_deployment_id_key (id)
```

**Comment by akme** [comment] 2020-11-25 21:46
Also it says that 1258 unused indices. Remove them for faster writes.

**Comment by lutter** [comment] 2020-11-25 22:01
You are right, that duplicate index on `subgraph_deployment(id)` should be dropped.

The 1258 unused indexes are a little more tricky: they will be unused as long as there is no query traffic. And quite a few of them will stay unused. But the ones that do get used are crucial for any sort of performance under decent load - if we got rid of all those indexes, indexers would quickly run into performance issues under load, and would have to figure out how to get rid of them. Neither situation is ideal, but for now overindexing seems preferable to indexer performance falling apart with real traffic.

**Comment by akme** [comment] 2020-11-25 22:07
Could you please provide a query that we should run to get rid of it correctly?
Will it be fixed on the code level so new setups won't create it again?

**Comment by legiojuve** [comment] 2020-11-26 10:10
> Could you please provide a query that we should run to get rid of it correctly?
> Will it be fixed on the code level so new setups won't create it again?

+

**Comment by trader-payne** [comment] 2020-11-26 11:28
@akme that isn't how database indexes work, from my understanding, but @lutter can correct me if I'm wrong here.

Indexes are created in order to boost the read/query performance.
More indexes - faster query time / slower data writes
They're valuing data serving over data gathering, basically, because the current logic of the graph-node is to overindex (hence why you have a few thousand indexes that were never used - as noticed by pg_stats).

If you want, you can manually create indexes from your topmost slow queries, if they are missing... or needed 🙂

**Comment by akme** [comment] 2020-11-26 11:30
@trader-payne yes, I understand that, so I created an issue only about duplicates, that 100% redundant.

**Comment by lutter** [comment] 2020-11-26 19:13
> Could you please provide a query that we should run to get rid of it correctly?
> Will it be fixed on the code level so new setups won't create it again?

The way to get rid of the duplicate index is with `drop index subgraphs.attr_2_0_subgraph_deployment_id` - I will make sure that the migration that drops it that we will ship one day will work regardless of whether that index is there or not.

As for indexes in general: as @trader-payne indicated, there's a tradeoff in terms of the usability of `graph-node` between  indexing everything and requiring every indexer to be very good at analyzing and fixing performance issues caused by missing indexes. For now, we are opting on the side of somewhat slower writes and requiring less in-depth knowledge from indexers. But there's definitely room for better tooling to make using fewer indexes feasible without a black belt in Postgres administration.

**Comment by avandras** [comment] 2024-03-28 09:49
@lutter I think this issue is long solved on the one hand (duplicates) and being addressed on the other hand (unused indexes).  Therefore we might want to close this.

**Closed** 2024-03-28 18:18 UTC
Labels: enhancement, performance
