### ISSUE TITLE
[RFC] subgraph syncing / recycling

### ISSUE THREAD

**Issue by sakulstra** [graphprotocol/graph-node#2143] opened 2021-01-28 14:57 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature/Idea

**What is the current behavior?**
Subgraph sync time is a major problem when working with thegraph.
For weth i read it's 24d, but for smaller thing like e.g. aave v1 it might also take multiple days.
While once synced things are fine, but the current resync behavior makes iterating on thegraph painful.

**What is the expected behavior?**
Development should be fun & fast :sweat_smile: - i don't want to wait days for a subgraph resync.

**Idea**
This might be nonsense as i'm very new to thegraph. Feel free to close this ticket if it is!

While I understand that initial syncing might be slow, I started wondering why resyncing is.

As I see it, most o the time, we don't add/alter the events we're listening to, but just how we process & store them.
Also a lot of subgraphs listen to some of the same events, but only diverge in processing them.
Shouldn't it be possible to essentially cache/store the raw event data **once** and then just recycle it instead of re-indexing via rpc from scratch on every resync? I guess this could even allow multiple subgraphs to share a common cache and skip the initial indexing?

Does this make sense? Appreciate any feedback.

**Comment by lutter** [comment] 2021-02-26 18:22
Thanks for the suggestion. This is a duplicate of #608

**Closed by lutter** 2021-02-26 18:22 UTC
