### ISSUE TITLE
Graph node stops processing any new events without any relevant log output

### ISSUE THREAD

**Issue by riordant** [graphprotocol/graph-node#4753] opened 2023-07-12 15:06 UTC
### Bug report

Hi,
We are having an issue syncing a graph node from a Tenderly devnet RPC endpoint.
The subgraph will initially sync no problem, but after a time (2-3 days) it will simply not pick up any new events.
Below is the relevant log.
I've tried running with traces but am not getting any useful information.
There doesn't seem to be anything wrong on the Tenderly side.
I have pasted the logs below.
Thanks

### Relevant log output

```Shell
Jul 12 11:21:00.622 DEBG no chain head update for 30 seconds, polling for update, sgd: 1, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: BlockStream
Jul 12 11:21:10.789 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 1, avg_hits: 0.00, entries: 1, network: mainnet, shard: 21, query_id: 63ce2e36927eab38-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:21:17.079 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 0, avg_hits: 2.00, entries: 1, network: mainnet, shard: 30, query_id: e5ead21bf3af99a8-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:21:30.624 DEBG no chain head update for 30 seconds, polling for update, sgd: 1, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: BlockStream
Jul 12 11:21:43.328 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 1, avg_hits: 0.00, entries: 1, network: mainnet, shard: 105, query_id: fd273feeb8fc6a4a-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:22:00.626 DEBG no chain head update for 30 seconds, polling for update, sgd: 1, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: BlockStream
Jul 12 11:22:25.127 INFO Syncing 1 blocks from Ethereum, code: BlockIngestionStatus, blocks_needed: 1, blocks_behind: 1, latest_block_head: 17669179, current_block_head: 17669178, provider: mainnet-rpc-0, component: BlockIngestor
Jul 12 11:22:25.952 DEBG 0 candidate triggers in this block, block_hash: 0x0a411415143508d74c8f86c8457aca4ca6e9b5f60bad7ba852312633a763ae0a, block_number: 17669179, sgd: 1, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: SubgraphInstanceManager
Jul 12 11:22:30.052 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 0, avg_hits: 10.00, entries: 1, network: mainnet, shard: 117, query_id: 63eb51b6753b1b-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:22:31.134 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 0, avg_hits: 2.00, entries: 1, network: mainnet, shard: 94, query_id: 1f3e67aa833ba7cf-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:22:31.196 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 0, avg_hits: 1.00, entries: 1, network: mainnet, shard: 4, query_id: d50c90dff4b8a02b-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:22:31.484 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 1, avg_hits: 0.00, entries: 1, network: mainnet, shard: 48, query_id: eedcc8fa2d1bda86-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner
Jul 12 11:22:32.546 DEBG Rotating query cache, stats for last block, avg_insert_time_ms: 0.00, fill_ratio: 0.00, dead_inserts: 0, avg_hits: 8.00, entries: 1, network: mainnet, shard: 37, query_id: e0050e8f979ee26e-6dc8c4ef99f8cc6a, subgraph_id: QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg, component: GraphQlRunner

```

It appears to not get any more data after `Syncing 1 blocks from Ethereum`. At the point data does not change, despite there being several transactions with events that should be processed.

### IPFS hash

QmSywszVLn7dZ7YEhzxyW36cJTbWhaoJQ4xidaKWNGArtg

### Subgraph name or link to explorer

https://spool-v2-testing.spool.fi/subgraphs/name/spool/core-v2/graphql

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

Linux

**Comment by azf20** [comment] 2023-08-09 12:06
Closing as duplicate of #4356

**Closed by azf20** 2023-08-09 12:06 UTC
Labels: bug
