### ISSUE TITLE
ABI matching for dynamic data sources

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-node#834] opened 2019-03-22 00:20 UTC
Our first pass at dynamic data sources assumes that the contract address that the user wants to subscribe to will be available to the mapping handler. There are certain situations where users will want to supply an ABI and dynamically subscribe to any contract that matches this ABI. This is especially important for ENS.

**Comment by Arachnid** [comment] 2019-03-22 06:28
I think this is a duplicate of https://github.com/graphprotocol/graph-node/issues/616

**Comment by Jannis** [comment] 2019-03-22 06:43
Thanks @arachnid, you're right. I'll close it as a duplicate.

Side note: this feature will become available for static and dynamic data sources equally.

**Closed by Jannis** 2019-03-22 06:43 UTC
Labels: adoption-blocker, area/runtime, enhancement
