### ISSUE TITLE
Block polling failed:  Error("missing field `gasPrice`")

### ISSUE THREAD

**Issue by danielpham765** [graphprotocol/graph-node#2609] opened 2021-07-02 07:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I got this error when running up a graph-node:

```sh
Jul 02 06:57:51.709 INFO Downloading latest blocks from Ethereum. This may take a few minutes..., network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.744 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #1) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.753 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #2) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.765 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #3) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.780 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #4) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.809 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #5) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.831 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #6) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:51.881 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #7) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:52.008 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #8) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:52.257 DEBG Trying again after eth_getBlockByHash RPC call failed (attempt #9) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:52.275 WARN Trying again after eth_getBlockByHash RPC call failed (attempt #10) with result Err(Decoder error: Error("missing field `gasPrice`", line: 0, column: 0)), network_name: ropsten, component: BlockIngestor
Jul 02 06:57:52.278 WARN Trying again after block polling failed: Decoder error: Error("missing field `gasPrice`", line: 0, column: 0), network_name: ropsten, component: BlockIngestor
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I run up a graph-node with docker-compose as below:

```yaml
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.23.1
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'ropsten:http://13.229.224.147:8545'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

```

My OpenEthereum full-node is running with prunning='archived' mode. It opens all traffics, and uses ports with default config.
And all JSON-RPC APIs work like a charm.

**What is the expected behavior?**

Graph-node runs up successfully.

**Comment by leoyvens** [comment] 2021-07-02 17:55
@danielpham765 what Ethereum network are you running against?

**Comment by tilacog** [comment] 2021-07-02 17:59
@danielpham765 can you provide a sample response from your Ethereum node for that method call?

**Comment by danielpham765** [comment] 2021-07-05 02:43
> @danielpham765 what Ethereum network are you running against?

I'm using Ropsten testnet with chainid=3

**Comment by danielpham765** [comment] 2021-07-05 02:53
> @danielpham765 can you provide a sample response from your Ethereum node for that method call?

Sure, many thanks for supporting me. 

Here is log of request `eth_getBlockByHash` on ETH node:

```log
2021-07-05 02:37:32 UTC http.worker00 TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce",true],"id":116878}.
2021-07-05 02:37:32 UTC http.worker00 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"author":"0x612d250c8e759d874ca3383ca75faf7ffc3cb933","baseFeePerGas":"0x7","difficulty":"0x26e470d4","extraData":"0xd883010a04846765746888676f312e31362e35856c696e7578","gasLimit":"0x7a1200","gasUsed":"0x5a101","hash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","logsBloom":"0x00000000000000000000000080000100000000000000000000000000000000000000000100000000000000000000000000008000000000000000000000000000000000000000000000000008800000400000000004000000080010000000000000000000000000000000000000000000000000000000040000000010000000000000000000000000000000000000000000002000000000000000200000000800000000000000000000000000001000000000004000000000000000000000000000000002000000000000000001000000000020000000000000000000000000000000000000000040004004000000000000000000000000000000000000000004","miner":"0x612d250c8e759d874ca3383ca75faf7ffc3cb933","mixHash":"0xf2ef7e43d4c717be1be2ed3f6d1bfa28a397f4b9f51768ff58cee760083e15ad","nonce":"0x31554be23d2b0d7e","number":"0xa14b39","parentHash":"0x159a23a9887cb62529c3089e299ed6f6fefdb493470fa85816399348ff4e63e1","receiptsRoot":"0xe1d8b34f4dda0c7b49539fd31f5527b101bd32ee4cd7d3aeb0b018a6a5f9b132","sealFields":["0xa0f2ef7e43d4c717be1be2ed3f6d1bfa28a397f4b9f51768ff58cee760083e15ad","0x8831554be23d2b0d7e"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x849","stateRoot":"0xab372ad2079cb3876681aaaf6d36c01696a4b22ea44c3e3110f15feef8201ed7","timestamp":"0x60e27048","totalDifficulty":"0x78add129c85592","transactions":[{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":"0x3","condition":null,"creates":null,"from":"0x81f87187235223c2eb194ea63b2b292332ef8f82","gas":"0x1e309","gasPrice":"0x2540be400","hash":"0xb27401dbb13a164dadcd8b2ed07abe48f3d5ae80d69f9bd3461d3f72faf5b429","input":"0x7ff36ab50000000000000000000000000000000000000000000000000000000000f28984000000000000000000000000000000000000000000000000000000000000008000000000000000000000000081f87187235223c2eb194ea63b2b292332ef8f8200000000000000000000000000000000000000000000000000000000617b06c50000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c778417e063141139fce010982780140aa0cd5ab000000000000000000000000dbc941fec34e8965ebc4a25452ae7519d6bdfc4e","nonce":"0x1a87a","publicKey":"0xc540cb597fb71902f5e6b297b55233a687faff93659a936ac7010bcbfc0c8d793958e5bb77844c6aa6e5bfb332b59cc08058b2b3e1030d8d3cedadf24abfc23e","r":"0xee672eda45a80aa0726285b9f3e601738b28f51e7ed527a5c18fc5b71410e6da","raw":"0xf901548301a87a8502540be4008301e309947a250d5630b4cf539739df2c5dacb4c659f2488d871813c86dccdb0bb8e47ff36ab50000000000000000000000000000000000000000000000000000000000f28984000000000000000000000000000000000000000000000000000000000000008000000000000000000000000081f87187235223c2eb194ea63b2b292332ef8f8200000000000000000000000000000000000000000000000000000000617b06c50000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c778417e063141139fce010982780140aa0cd5ab000000000000000000000000dbc941fec34e8965ebc4a25452ae7519d6bdfc4e2aa0ee672eda45a80aa0726285b9f3e601738b28f51e7ed527a5c18fc5b71410e6daa05109ec0df10c398808cd022f73b1938fee2d7af373f1164089b9a9a54062d032","s":"0x5109ec0df10c398808cd022f73b1938fee2d7af373f1164089b9a9a54062d032","standardV":"0x1","to":"0x7a250d5630b4cf539739df2c5dacb4c659f2488d","transactionIndex":"0x0","v":"0x2a","value":"0x1813c86dccdb0b"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":"0x3","condition":null,"creates":null,"from":"0xe75eaad190174d2a10378f419c622c2137915076","gas":"0x1e8480","gasPrice":"0x94efe621","hash":"0x70da78c7682729ef90c15f309c5f608f467cc70687fe4d391011de47545ef9af","input":"0x","nonce":"0x2","publicKey":"0xbecd969268a39e3da032b717b65693fe390ea99d1ed7597515b9c31f779a81964f63c14c8b3a7409b6a293a7854d915e965507f5d925facddabb1ea01cb10640","r":"0x149e4a89f5f9805bb4b5005be068517610cc88faaae93bbfd99f6d3511809a4c","raw":"0xf86c028494efe621831e8480941989b73cfb9996bf018ade21e4b5c126ba11f3d0881bc13dadcf923cf8802aa0149e4a89f5f9805bb4b5005be068517610cc88faaae93bbfd99f6d3511809a4ca04263ece8122a05cc40c70d2806194a1c9153f28e710ba7d58e14897c92ea046c","s":"0x4263ece8122a05cc40c70d2806194a1c9153f28e710ba7d58e14897c92ea046c","standardV":"0x1","to":"0x1989b73cfb9996bf018ade21e4b5c126ba11f3d0","transactionIndex":"0x1","v":"0x2a","value":"0x1bc13dadcf923cf8"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":"0x3","condition":null,"creates":null,"from":"0x1b6cd10974a55a62130b7efd85e057cdd7fb49d8","gas":"0x1e8480","gasPrice":"0x94efe621","hash":"0x7289c1d307cbea471c3e14ca8dba1ba41f4874db171226f9ed1ae4de41e72267","input":"0x","nonce":"0x0","publicKey":"0x9978f7a564305de6b45de0fdc10d12cac408c285d2c7e1b72bea985507bca6bf4b4e2fcb3e74cdac5c57271049587a3067b966e4740ae77f1be374970b6ea8b4","r":"0xc31b37238364d1fd7c9dccc69aa203dc403384ed9bfa87d8b331b696b62c05fa","raw":"0xf86c808494efe621831e8480941989b73cfb9996bf018ade21e4b5c126ba11f3d0880d2ee43df9693cf8802aa0c31b37238364d1fd7c9dccc69aa203dc403384ed9bfa87d8b331b696b62c05faa019f504ade43e5e5dd0744d02ac306b7458fe7fced26ccf70cbec873bf590ca23","s":"0x19f504ade43e5e5dd0744d02ac306b7458fe7fced26ccf70cbec873bf590ca23","standardV":"0x1","to":"0x1989b73cfb9996bf018ade21e4b5c126ba11f3d0","transactionIndex":"0x2","v":"0x2a","value":"0xd2ee43df9693cf8"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":"0x3","condition":null,"creates":null,"from":"0x1cc8218e9bf382f6ada55005f3a46ad4ed0410ed","gas":"0x5208","gasPrice":"0x772651c0","hash":"0xbafe7d8187bce6e4a543c5c27d35b864017fbe39dfabaab7421cc3caf4f820f0","input":"0x","nonce":"0x1d","publicKey":"0xa8fd8e425e4e50c36b0e6c722dbe0f9310a90e228f12f15b23d044c56d184738db5075c1dd494a6a1b182753e76e775499c7d5f45252dab18652e306575b114e","r":"0x16804bdb3b0d7f3d0692d112d1891a346858bb77d036fa2f2a1216da7ecb97fd","raw":"0xf86a1d84772651c0825208941a836b1b34e02bf928c95a9405556a955903952d872386f26fc10000802aa016804bdb3b0d7f3d0692d112d1891a346858bb77d036fa2f2a1216da7ecb97fda0776c334a4ddc8de3a5c61bf4e20302017c0937375bd8d26e19533ed029cc4dfa","s":"0x776c334a4ddc8de3a5c61bf4e20302017c0937375bd8d26e19533ed029cc4dfa","standardV":"0x1","to":"0x1a836b1b34e02bf928c95a9405556a955903952d","transactionIndex":"0x3","v":"0x2a","value":"0x2386f26fc10000"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":null,"condition":null,"creates":null,"from":"0x81b7e08f65bdf5648606c89998a9cc8164397647","gas":"0x5208","gasPrice":"0x772651b4","hash":"0x888460c15a76c21a06f2af05fc90683421dfd0d9bd0e6e1056b45d55fd669085","input":"0x","nonce":"0x248b69b","publicKey":"0xe5af5959ae17550b2fe7bac2cde9dbae548c25033bdf71da03edb5cadda34baad4d60d47f8051f2f056c3156f68f9972c77a43e93434e8281f35290f417c6df4","r":"0xb72b5f8eab613db79e4a3a4b3e03c0ee48e9e20db09315330155be39ea0cd742","raw":"0xf86f840248b69b84772651b482520894605b9d73bb63f05badfaba5582852ce0920f7117880de0b6b3a7640000801ca0b72b5f8eab613db79e4a3a4b3e03c0ee48e9e20db09315330155be39ea0cd742a032c93ddd4a9a8c2cd9f82109b65ff16105e71ead0fcff462e376a9830c0ec0ee","s":"0x32c93ddd4a9a8c2cd9f82109b65ff16105e71ead0fcff462e376a9830c0ec0ee","standardV":"0x1","to":"0x605b9d73bb63f05badfaba5582852ce0920f7117","transactionIndex":"0x4","v":"0x1c","value":"0xde0b6b3a7640000"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":"0x3","condition":null,"creates":null,"from":"0x52fc873b9b68a9570a4a674f8f7d2a01e1dc3293","gas":"0xf7d1","gasPrice":"0x772651b4","hash":"0x4991c17bc75c3fe56217a3be6a8cc99070f389a21002b8cf15b5d6fd2745af13","input":"0xa9059cbb000000000000000000000000f2c3c2fecaf758ee80f50345d77dbb76895b93be0000000000000000000000000000000000000000000000000000000000002710","nonce":"0x644","publicKey":"0x45260a643241ea411ab27b5854f338f4a429e766e983ede14cc908694279e36fa3bc326d59e8a6aa4d37739226c21903caf273cdc7f40dd6fb1201c94a046dfa","r":"0x725a55e73c9728436cf998d1c59df7a7c3c5e16847dc7af1b279044ac16ff931","raw":"0xf8aa82064484772651b482f7d194b3d58b9b4509b6d2f6ffb113a57e3c6014ed890f80b844a9059cbb000000000000000000000000f2c3c2fecaf758ee80f50345d77dbb76895b93be000000000000000000000000000000000000000000000000000000000000271029a0725a55e73c9728436cf998d1c59df7a7c3c5e16847dc7af1b279044ac16ff931a01b09d326f95069621fc53d721bc5f4c165ba140069ce4f576d2b967a08f2f03c","s":"0x1b09d326f95069621fc53d721bc5f4c165ba140069ce4f576d2b967a08f2f03c","standardV":"0x0","to":"0xb3d58b9b4509b6d2f6ffb113a57e3c6014ed890f","transactionIndex":"0x5","v":"0x29","value":"0x0"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":null,"condition":null,"creates":null,"from":"0x81b7e08f65bdf5648606c89998a9cc8164397647","gas":"0x5208","gasPrice":"0x772651b4","hash":"0xf11bacbb6e84d60535c533a992385145e3607599201e86fe8462dd69af966aaf","input":"0x","nonce":"0x248b69c","publicKey":"0xe5af5959ae17550b2fe7bac2cde9dbae548c25033bdf71da03edb5cadda34baad4d60d47f8051f2f056c3156f68f9972c77a43e93434e8281f35290f417c6df4","r":"0x5d25fc256fac84c7fb3d5abc06cfad5224f3c912479e2975d78e5306e4d866f1","raw":"0xf86f840248b69c84772651b482520894d0a10f73926cebd7dc209ff89ec893adcd007fb6880de0b6b3a7640000801ba05d25fc256fac84c7fb3d5abc06cfad5224f3c912479e2975d78e5306e4d866f1a03c10856795b33ed4163b47a53a65ac9dd749b073f2696a898d685b0df2e7ab20","s":"0x3c10856795b33ed4163b47a53a65ac9dd749b073f2696a898d685b0df2e7ab20","standardV":"0x0","to":"0xd0a10f73926cebd7dc209ff89ec893adcd007fb6","transactionIndex":"0x6","v":"0x1b","value":"0xde0b6b3a7640000"},{"blockHash":"0xae93809ae0796beb9791f233cc44b9f255d946e479d12d95927f3e68a26c7cce","blockNumber":"0xa14b39","chainId":null,"condition":null,"creates":null,"from":"0x81b7e08f65bdf5648606c89998a9cc8164397647","gas":"0x5208","gasPrice":"0x772651b4","hash":"0x9447f51e9264beceaac7571cede4bb71210e5255cfdaf27918000db11a0b4e42","input":"0x","nonce":"0x248b69d","publicKey":"0xe5af5959ae17550b2fe7bac2cde9dbae548c25033bdf71da03edb5cadda34baad4d60d47f8051f2f056c3156f68f9972c77a43e93434e8281f35290f417c6df4","r":"0xcf2a0e26a461f5cf958fb0774c44a156a999cd057a26e3262c3cd218aba463c1","raw":"0xf86f840248b69d84772651b482520894b71377379fa555c92c3d945e4457c2adcebe6d41880de0b6b3a7640000801ca0cf2a0e26a461f5cf958fb0774c44a156a999cd057a26e3262c3cd218aba463c1a00e411d27480df53f3544422da@@@
```

**Comment by danielpham765** [comment] 2021-07-05 02:58
I realized that this error doesn't affect to graph-node at all. After a period of time, it's downloaded the latest blocks from Ethereum successfully. But these debug/warn logs are still printed continuously.

**Comment by schmidsi** [comment] 2021-07-05 11:38
> I realized that this error doesn't affect to graph-node at all. After a period of time, it's downloaded the latest blocks from Ethereum successfully. But these debug/warn logs are still printed continuously.

Hmm, then it is expected behaviour. Graph-node retries that query until it gets a good answer. The question is, why does your archive node not responding correctly from the beginning? Have you tried Erigon?

Closing this, because it is expected behaviour from the graph-node. Feel free to reopen.

**Closed by schmidsi** 2021-07-05 11:38 UTC
