### ISSUE TITLE
On the hosted service, loading subgraph files from IPFS sometimes times out

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-node#823] opened 2019-03-13 18:06 UTC
The pending version of the subgraph is stuck here:
https://thegraph.com/explorer/subgraph/davekaj/new-decentraland

@lutter  looked into it, and noticed that it was assigned to index_node_mainnet_2, but was sitting at block 0. The error in the subgraph log said:
`Subgraph instance failed to start, subgraph_id: QmTAK6LJ5GPZzRtv6598UzRV8UqonMTUF5bgUY3TtG4hg9, error: subgraph resolve error: resolve error: deadline has elapsed
`

It seems we had trouble getting the manifest off IPFS, but the subgraph never gets marked as failed, and on my local machine I get a returned response of a successful deployment.

**Comment by davekaj** [comment] 2019-03-13 18:09
After re-deploying with a different subgraphID (added a line to manifest) it worked. 

Looks like to fix this issue we should give some sort of indication in the UI that this subgraph is failed, not stuck at 0. 

Also, the logs were not showing up at all in the UI, the only way we figured out the error was from lutter looking into it in the backend

**Comment by leodasvacas** [comment] 2019-03-13 22:02
#824 made this set the subgraph to failed, but we still need to get the logs through.

**Comment by Jannis** [comment] 2019-06-26 18:18
This has been resolved. We've both identified the root cause for this and added more detailed logging about resolving subgraph files via IPFS.

**Closed by Jannis** 2019-06-26 18:18 UTC
Labels: area/subgraphs, bug
