### ISSUE TITLE
implementation Graph-node on Cronos failed

### ISSUE THREAD

**Issue by PhantomTop** [graphprotocol/graph-node#3099] opened 2021-12-27 02:55 UTC
**Do you want to request a *feature* or report a *bug*?**
This is bug.
**What is the current behavior?**
Current Command:
graph-node --postgres-url postgresql://postgres:aaa@localhost:5432/graphnodedb --ethereum-rpc mainnet:https://evm-cronos.crypto.org --ipfs 127.0.0.1:5001 --http-port 80

![image](https://user-images.githubusercontent.com/95626405/147429628-1c5836ed-5ad8-444f-abc6-8fa7a0947385.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When I run cronos local node, graph-node sync blocks at first, but after a few hour, it fails with rpc error.

**What is the expected behavior?**
It must be run without error.

**Comment by maoueh** [comment] 2022-01-04 20:54
Assuming this is a duplicate of #3086, closing. Re-open if it's a different issue.

**Closed by maoueh** 2022-01-04 20:54 UTC
