### ISSUE TITLE
Handle block with intervals

### ISSUE THREAD

**Issue by milonite** [graphprotocol/graph-node#2392] opened 2021-04-20 11:09 UTC
**Do you want to request a *feature* or report a *bug*?**

  feature

**What is the current behavior?**
Block handlers run on each block

**What is the expected behavior?**
Since block handlers have a big impact on indexing time, would be great to have an out-of-the-box handler to define an arbitrary block interval. E.g: for 10 blocks

```
blockHandlers
   - handler: handleBlockWithInterval
     interval: 10
```
  
#959

**Comment by fubhy** [comment] 2021-04-21 13:14
Duplicate of https://github.com/graphprotocol/graph-node/issues/959 - Please add a `thumbs up` to that issue and/or add a comment there if you want to voice your support or contribute some nuance/feedback for that feature request!

**Closed** 2021-04-21 14:00 UTC
