### ISSUE TITLE
Cannot find function signature when the return type is an array of structs

### ISSUE THREAD

**Issue by jeffywu** [graphprotocol/graph-node#1765] opened 2020-07-03 14:47 UTC
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Getting this error but the function signature is in the ABI:
```
Subgraph instance failed to run: Failed to process trigger in block #19382232 (3ff10cd5cf8235f06c7856cf5c68cd438dfe9f3705d61819987ab3609fc49c94), transaction fa190c24d292d50b06d23ab3a79d34668fb72a716d9610910f8f671aa38fab3f: Failed to invoke handler 'handleSettleAccount': Unknown function "Portfolios::getTrades" with signature `getTrades(address):(tuple[])` called from WASM runtime wasm backtrace: 0: 0x19fd - <unknown>!<wasm function 68> 1: 0x2270 - <unknown>!<wasm function 102> 2: 0x232a - <unknown>!<wasm function 106> 3: 0x23ab - <unknown>!<wasm function 108> 4: 0x2434 - <unknown>!<wasm function 109> , code: SubgraphSyncingFailure, id: QmfTD1uMk5zaghLCZSWR8Z2Vm9teVQDgQR3P5fVQCzZdPA
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Here is the relevant section of the ABI:
```
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "getTrades",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint8",
            "name": "instrumentGroupId",
            "type": "uint8"
          },
          {
            "internalType": "uint16",
            "name": "instrumentId",
            "type": "uint16"
          },
          {
            "internalType": "uint32",
            "name": "startBlock",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "duration",
            "type": "uint32"
          },
          {
            "internalType": "bytes1",
            "name": "swapType",
            "type": "bytes1"
          },
          {
            "internalType": "uint32",
            "name": "rate",
            "type": "uint32"
          },
          {
            "internalType": "uint128",
            "name": "notional",
            "type": "uint128"
          }
        ],
        "internalType": "struct Common.Trade[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
```

**What is the expected behavior?**
It should be able to find this function and call it.

**Comment by Jannis** [comment] 2020-07-21 11:34
Duplicate of #1800.

**Closed by Jannis** 2020-07-21 11:34 UTC
